### PR TITLE
Bumping version constraints

### PR DESCRIPTION
**Pull request by SwiftsNamesake**
As promised, new version constraints. I also had to bump the version number, obviously.

### CODE REVIEW

**Comment by bch29** [comment]
Does this require bumping to `1.3` rather than `1.2.3`?

**Comment by SwiftsNamesake** [comment]
I would've thought that changing several constraints to (possibly) incompatible version ranges was a breaking change. Hence the major-version bump (cf. [this](http://hackage.haskell.org/package/cabal-constraints-0.0.0.1/candidate/cabal-constraints.cabal) file).

**Comment by yehoshuapw** [comment]
+1

**Comment by plredmond** [comment]
Why did we change from version ranges to exact major.minor.* versions? Is there a reason not to use, eg `base >=4.7 && <4.10,` that I'm unaware of?

**Comment by SwiftsNamesake** [comment]
Maybe I was being overly cautious, but aren't the first two numbers reserved for breaking API-changes?
I'll loosen the constraints if you want me to.

**Comment by plredmond** [comment]
Yes, you're right, but if GPipe-GLFW still works with those older versions, there's no reason to explicitly remove support. I think we should follow [GPipe-Core's approach](https://github.com/tobbebex/GPipe-Core/blob/master/GPipe-Core/GPipe.cabal#L24) here.

**Pull request merged**
